"""creating tables for production

Revision ID: 02899d1ef626
Revises: 22086ac8a5bd
Create Date: 2024-03-27 09:05:27.326225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02899d1ef626'
down_revision: Union[str, None] = '22086ac8a5bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendors', 'business_social_links',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.drop_column('vendors', 'phone_no')
    op.alter_column('buyers', 'social_media_platform',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
