"""drop user table production

Revision ID: 0d61f9847ef6
Revises: 59b44b7d5953
Create Date: 2024-04-06 08:41:48.961065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d61f9847ef6'
down_revision: Union[str, None] = '59b44b7d5953'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('vendors')
    op.drop_table('buyers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'user_type')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###
