"""adding unique constraint to business name

Revision ID: 22086ac8a5bd
Revises: c8a020849a79
Create Date: 2024-03-27 00:47:13.606351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22086ac8a5bd'
down_revision: Union[str, None] = 'c8a020849a79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('vendors_business_bio_key', 'vendors', type_='unique')
    op.create_unique_constraint(None, 'vendors', ['business_name'])
    op.create_unique_constraint(None, 'vendors', ['vendor_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendors', type_='unique')
    op.drop_constraint(None, 'vendors', type_='unique')
    op.create_unique_constraint('vendors_business_bio_key', 'vendors', ['business_bio'])
    # ### end Alembic commands ###
