"""dropping all tables

Revision ID: 2aa5e56cf446
Revises: 6eda4fe342ab
Create Date: 2024-04-06 10:18:31.580724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aa5e56cf446'
down_revision: Union[str, None] = '6eda4fe342ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('vendors')
    op.drop_table('buyers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
