"""creating tables

Revision ID: 38c014c3c921
Revises: b5585ae7388b
Create Date: 2024-03-25 17:49:53.247834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38c014c3c921'
down_revision: Union[str, None] = 'b5585ae7388b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buyers', sa.Column('buyer_id', sa.String(), nullable=False))
    op.add_column('buyers', sa.Column('profile_picture', sa.String(), server_default='N/A', nullable=False))
    op.create_unique_constraint(None, 'buyers', ['buyer_id'])
    op.drop_column('buyers', 'user_id')
    op.add_column('vendors', sa.Column('profile_picture', sa.String(), server_default='N/A', nullable=False))
    op.create_unique_constraint(None, 'vendors', ['vendor_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendors', type_='unique')
    op.drop_column('vendors', 'profile_picture')
    op.add_column('buyers', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'buyers', type_='unique')
    op.drop_column('buyers', 'profile_picture')
    op.drop_column('buyers', 'buyer_id')
    # ### end Alembic commands ###
