"""social_media_platform column

Revision ID: 514cf2e8d36a
Revises: 4ceb57e8bf0e
Create Date: 2024-03-26 16:03:57.712587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '514cf2e8d36a'
down_revision: Union[str, None] = '4ceb57e8bf0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('buyers', 'social_media_platform',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
