"""creating the orders and disputes table

Revision ID: 5e366c38f7cf
Revises: b5ad2881a176
Create Date: 2024-04-14 19:55:25.499376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e366c38f7cf'
down_revision: Union[str, None] = 'b5ad2881a176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'disputes', ['dispute_id'])
    op.drop_constraint('disputes_order_id_fkey', 'disputes', type_='foreignkey')
    op.create_foreign_key(None, 'disputes', 'orders', ['order_id'], ['order_id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'orders', ['order_id'])
    op.drop_constraint('orders_vendor_id_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_buyer_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'buyers', ['buyer_id'], ['buyer_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'orders', 'vendors', ['vendor_id'], ['vendor_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_buyer_id_fkey', 'orders', 'buyers', ['buyer_id'], ['buyer_id'])
    op.create_foreign_key('orders_vendor_id_fkey', 'orders', 'vendors', ['vendor_id'], ['vendor_id'])
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_constraint(None, 'disputes', type_='foreignkey')
    op.create_foreign_key('disputes_order_id_fkey', 'disputes', 'orders', ['order_id'], ['order_id'])
    op.drop_constraint(None, 'disputes', type_='unique')
    # ### end Alembic commands ###
