"""adding phone_no to vendors

Revision ID: 622c52e2c856
Revises: 308f0aef0728
Create Date: 2024-03-27 00:38:58.423319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '622c52e2c856'
down_revision: Union[str, None] = '308f0aef0728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendors', 'business_social_links',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.drop_column('vendors', 'phone_no')
    op.drop_constraint(None, 'buyers', type_='unique')
    # ### end Alembic commands ###
