"""dropping the tables

Revision ID: 743f3fb996a4
Revises: 02899d1ef626
Create Date: 2024-03-27 09:08:55.497699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '743f3fb996a4'
down_revision: Union[str, None] = '02899d1ef626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buyers')
    op.drop_table('vendors')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendors', 'business_social_links',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.drop_column('vendors', 'phone_no')
    op.alter_column('buyers', 'social_media_platform',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
