"""creating all tables

Revision ID: 8a728c5169e1
Revises: 
Create Date: 2024-05-13 22:34:30.913930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a728c5169e1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyers',
    sa.Column('buyer_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), server_default='N/A', nullable=False),
    sa.Column('date_of_birth', sa.String(), server_default='N/A', nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('city', sa.String(), server_default='N/A', nullable=False),
    sa.Column('gender', sa.String(), server_default='N/A', nullable=False),
    sa.Column('country', sa.String(), server_default='N/A', nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('phone_no', sa.String(), server_default='N/A', nullable=False),
    sa.Column('bought_fake', sa.String(), server_default='N/A', nullable=False),
    sa.Column('social_media_platform', sa.JSON(), nullable=True),
    sa.Column('is_scammed', sa.String(), server_default='N/A', nullable=False),
    sa.Column('use_venduit', sa.String(), server_default='N/A', nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('shopping', sa.String(), server_default='N/A', nullable=False),
    sa.Column('profile_picture', sa.String(), server_default='N/A', nullable=False),
    sa.Column('user_type', sa.String(), server_default='buyer', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('buyer_id'),
    sa.UniqueConstraint('buyer_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('user_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'email'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('vendors',
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), server_default='N/A', nullable=False),
    sa.Column('date_of_birth', sa.String(), server_default='N/A', nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), server_default='N/A', nullable=False),
    sa.Column('city', sa.String(), server_default='N/A', nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('phone_no', sa.String(), server_default='N/A', nullable=False),
    sa.Column('business_name', sa.String(), server_default='N/A', nullable=False),
    sa.Column('business_bio', sa.String(), server_default='N/A', nullable=False),
    sa.Column('business_category', sa.String(), server_default='N/A', nullable=False),
    sa.Column('business_reach', sa.String(), server_default='N/A', nullable=False),
    sa.Column('business_social_links', sa.JSON(), nullable=True),
    sa.Column('business_startDate', sa.String(), server_default='N/A', nullable=False),
    sa.Column('business_logo', sa.String(), server_default='N/A', nullable=False),
    sa.Column('is_scammed', sa.String(), server_default='N/A', nullable=False),
    sa.Column('use_venduit', sa.String(), server_default='N/A', nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('country', sa.String(), server_default='N/A', nullable=False),
    sa.Column('profile_picture', sa.String(), server_default='N/A', nullable=False),
    sa.Column('user_type', sa.String(), server_default='vendor', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('vendor_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('vendor_id')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_dispute', sa.Boolean(), nullable=False),
    sa.Column('buyer_id', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.buyer_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.vendor_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_orders_order_id'), 'orders', ['order_id'], unique=True)
    op.create_table('disputes',
    sa.Column('dispute_id', sa.String(), nullable=False),
    sa.Column('dispute_category', sa.String(), nullable=False),
    sa.Column('dispute_desc', sa.String(), server_default='N/A', nullable=True),
    sa.Column('status', sa.String(), server_default='N/A', nullable=False),
    sa.Column('dispute_image', sa.String(), server_default='N/A', nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dispute_id'),
    sa.UniqueConstraint('dispute_id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('product_desc', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=False),
    sa.Column('product_image', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_table('disputes')
    op.drop_index(op.f('ix_orders_order_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('vendors')
    op.drop_table('users')
    op.drop_table('buyers')
    # ### end Alembic commands ###
