"""drop orders and disputes table

Revision ID: bbf157cf723f
Revises: 52bca1f0f29c
Create Date: 2024-04-14 18:49:24.857627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbf157cf723f'
down_revision: Union[str, None] = '52bca1f0f29c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_table("disputes")
    op.drop_table("orders")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
