"""creating vendor table again

Revision ID: c8a020849a79
Revises: 622c52e2c856
Create Date: 2024-03-27 00:40:54.404467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8a020849a79'
down_revision: Union[str, None] = '622c52e2c856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors',
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('phone_no', sa.String(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=False),
    sa.Column('business_bio', sa.String(), nullable=False),
    sa.Column('business_category', sa.String(), nullable=False),
    sa.Column('business_reach', sa.String(), nullable=False),
    sa.Column('business_social_links', sa.JSON(), nullable=True),
    sa.Column('business_startDate', sa.String(), nullable=False),
    sa.Column('business_logo', sa.String(), server_default='N/A', nullable=False),
    sa.Column('is_scammed', sa.String(), nullable=False),
    sa.Column('use_venduit', sa.String(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('profile_picture', sa.String(), server_default='N/A', nullable=False),
    sa.Column('user_type', sa.String(), server_default='vendor', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('vendor_id'),
    sa.UniqueConstraint('business_bio'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('vendor_id')
    )
    op.create_unique_constraint(None, 'buyers', ['buyer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'buyers', type_='unique')
    op.drop_table('vendors')
    # ### end Alembic commands ###
