"""creating vendor table again

Revision ID: c8a020849a79
Revises: 622c52e2c856
Create Date: 2024-03-27 00:40:54.404467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8a020849a79'
down_revision: Union[str, None] = '622c52e2c856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'buyers', type_='unique')
    op.drop_table('vendors')
    # ### end Alembic commands ###
