"""Adding server default to users and vendor table

Revision ID: d19023fc8c93
Revises: 74ca5d7c56e3
Create Date: 2024-04-06 10:38:29.569489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd19023fc8c93'
down_revision: Union[str, None] = '74ca5d7c56e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'buyers', ['buyer_id'])
    op.create_unique_constraint(None, 'vendors', ['vendor_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendors', type_='unique')
    op.drop_constraint(None, 'buyers', type_='unique')
    # ### end Alembic commands ###
