"""creating the order and dispute table

Revision ID: d46d627eef9b
Revises: 0baef359265c
Create Date: 2024-04-14 01:49:06.872777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd46d627eef9b'
down_revision: Union[str, None] = '0baef359265c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('product_desc', sa.String(), server_default='N/A', nullable=True),
    sa.Column('status', sa.String(), server_default='Ordered', nullable=False),
    sa.Column('price', sa.String(), nullable=False),
    sa.Column('product_image', sa.String(), server_default='N/A', nullable=False),
    sa.Column('is_dispute', sa.Boolean(), nullable=False),
    sa.Column('buyer_id', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.vendor_id'], ),
    sa.PrimaryKeyConstraint('order_id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('disputes',
    sa.Column('dispute_id', sa.String(), nullable=False),
    sa.Column('dispute_category', sa.String(), nullable=False),
    sa.Column('dispute_desc', sa.String(), server_default='N/A', nullable=True),
    sa.Column('status', sa.String(), server_default='N/A', nullable=False),
    sa.Column('dispute_image', sa.String(), server_default='N/A', nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('dispute_id'),
    sa.UniqueConstraint('dispute_id')
    )
    op.create_unique_constraint(None, 'buyers', ['buyer_id'])
    op.create_unique_constraint(None, 'vendors', ['vendor_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendors', type_='unique')
    op.drop_constraint(None, 'buyers', type_='unique')
    op.drop_table('disputes')
    op.drop_table('orders')
    # ### end Alembic commands ###
