"""Adding server default to users and vendor table

Revision ID: ee31345b1136
Revises: d19023fc8c93
Create Date: 2024-04-06 10:40:22.765002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee31345b1136'
down_revision: Union[str, None] = 'd19023fc8c93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   op.drop_table('buyers')
   op.drop_table('vendors')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
